import time

print("Bem vindo à entrevista!")
time.sleep(1)
print("-" * 30)
print("A entrevista consistirá em 20 perguntas de múltipla escolha, \n")
time.sleep(0.5)
print("-" * 50)
print("cada uma com 4 alternativas (A, B, C, D). \n")
time.sleep(1.5)
print("-" * 50)
print("Ao final, você irá saber se você passou ou não na entrevista. \n")
time.sleep(1.5)
print("-" * 50)
print("Boa sorte! e vamos começar!")
print("-" * 50)
print("Começando...")
time.sleep(2)
print(" " * 100)